BIN+=arrayone
BIN+=string
BIN+=instr1
BIN+=instr2
BIN+=instr3
BIN+=numstr
BIN+=strtype1
BIN+=strtype2
BIN+=strtype3
BIN+=strtype4
BIN+=rawstr
BIN+=structur
BIN+=assgn_st
BIN+=arrstr
BIN+=bitfield
BIN+=address

CXXFLAGS+=-std=c++11

all: $(BIN)

.PYTHON: clean

clean:
	-rm -f $(BIN)
